# Generated by Django 5.0.4 on 2024-05-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_address_teacher_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='featured_image',
            field=models.ImageField(null=True, upload_to='courses_images/'),
        ),
        migrations.AddField(
            model_name='course',
            name='technologies',
            field=models.TextField(null=True),
        ),
    ]
