# Generated by Django 5.0.4 on 2024-05-04 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_modules'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modules',
            old_name='remakrs',
            new_name='remarks',
        ),
    ]
