# Generated by Django 5.0.4 on 2024-05-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_notification_notif_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='student_images'),
        ),
    ]
