# Generated by Django 5.0.4 on 2024-05-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_quiz_coursequiz_quizquestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestions',
            name='ans1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='ans2',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='ans3',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='ans4',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='right_ans',
            field=models.CharField(max_length=200),
        ),
    ]
