# Generated by Django 5.0.4 on 2024-06-20 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_attemptedquiz_submitted_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptedquiz',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.quiz'),
        ),
    ]
